const ENV = process.env.ENV
const BITPORTAL_API_REST_URL = process.env.BITPORTAL_API_REST_URL
const BITPORTAL_API_MARKET_URL = process.env.BITPORTAL_API_MARKET_URL
const BITPORTAL_API_WEBSOCKET_URL = process.env.BITPORTAL_API_WEBSOCKET_URL
const EOS_API_URL = process.env.EOS_API_URL
const BITPORTAL_API_CMS_URL = process.env.BITPORTAL_API_CMS_URL
const BITPORTAL_API_TERMS_URL = process.env.BITPORTAL_API_TERMS_URL
const BITPORTAL_API_UPDATE_LOG_URL = process.env.BITPORTAL_API_UPDATE_LOG_URL
const CURRENCY_RATE_URL = process.env.CURRENCY_RATE_URL
const EOS_EXPLORER_URL = process.env.EOS_EXPLORER_URL
const BITPORTAL_API_EOS_URL = process.env.BITPORTAL_API_EOS_URL
const BITPORTAL_WEBSITE_URL = process.env.BITPORTAL_WEBSITE_URL

export {
  ENV,
  BITPORTAL_API_REST_URL,
  BITPORTAL_API_MARKET_URL,
  BITPORTAL_API_WEBSOCKET_URL,
  EOS_API_URL,
  BITPORTAL_API_CMS_URL,
  BITPORTAL_API_TERMS_URL,
  BITPORTAL_API_UPDATE_LOG_URL,
  CURRENCY_RATE_URL,
  EOS_EXPLORER_URL,
  BITPORTAL_API_EOS_URL,
  BITPORTAL_WEBSITE_URL
}
