import Config from 'react-native-config'

const ENV = Config.ENV
const BITPORTAL_API_REST_URL = Config.BITPORTAL_API_REST_URL
const BITPORTAL_API_WEBSOCKET_URL = Config.BITPORTAL_API_WEBSOCKET_URL
const EOS_API_URL = Config.EOS_API_URL
const BITPORTAL_API_CMS_URL = Config.BITPORTAL_API_CMS_URL
const BITPORTAL_API_TERMS_URL = Config.BITPORTAL_API_TERMS_URL
const BITPORTAL_API_UPDATE_LOG_URL = Config.BITPORTAL_API_UPDATE_LOG_URL
const CURRENCY_RATE_URL = Config.CURRENCY_RATE_URL
const EOS_EXPLORER_URL=Config.EOS_EXPLORER_URL

export {
  ENV,
  BITPORTAL_API_REST_URL,
  BITPORTAL_API_WEBSOCKET_URL,
  EOS_API_URL,
  BITPORTAL_API_CMS_URL,
  BITPORTAL_API_TERMS_URL,
  BITPORTAL_API_UPDATE_LOG_URL,
  CURRENCY_RATE_URL,
  EOS_EXPLORER_URL
}
