import {
  ENV,
  BITPORTAL_API_REST_URL,
  BITPORTAL_API_WEBSOCKET_URL,
  EOS_API_URL,
  BITPORTAL_API_CMS_URL,
  BITPORTAL_API_TERMS_URL
} from './production'

export {
  ENV,
  BITPORTAL_API_REST_URL,
  BITPORTAL_API_WEBSOCKET_URL,
  EOS_API_URL,
  BITPORTAL_API_CMS_URL,
  BITPORTAL_API_TERMS_URL
}
