import Config from 'react-native-config'

const ENV = Config.ENV
const BITPORTAL_API_REST_URL = Config.BITPORTAL_API_REST_URL
const BITPORTAL_API_MARKET_URL = Config.BITPORTAL_API_MARKET_URL
const BITPROTAL_API_TRACE_URL = Config.BITPROTAL_API_TRACE_URL
const BITPORTAL_API_WEBSOCKET_URL = Config.BITPORTAL_API_WEBSOCKET_URL
const EOS_API_URL = Config.EOS_API_URL
const BITPORTAL_API_CMS_URL = Config.BITPORTAL_API_CMS_URL
const BITPORTAL_API_TERMS_URL = Config.BITPORTAL_API_TERMS_URL
const BITPORTAL_API_UPDATE_LOG_URL = Config.BITPORTAL_API_UPDATE_LOG_URL
const CURRENCY_RATE_URL = Config.CURRENCY_RATE_URL
const EOS_EXPLORER_URL = Config.EOS_EXPLORER_URL
const BITPORTAL_API_EOS_URL = Config.BITPORTAL_API_EOS_URL
const BITPORTAL_WEBSITE_URL = Config.BITPORTAL_WEBSITE_URL
const RIO_CHAIN_API = Config.RIO_CHAIN_API
const ADMIN_API = Config.ADMIN_API
const SCAN_API = Config.SCAN_API
const DEFAULT_DECIMALS = Config.DEFAULT_DECIMALS
const SS58FORMAT_PREFIX = Config.SS58FORMAT_PREFIX
const IS_MAINNET = Config.IS_MAINNET

export {
  ENV,
  BITPORTAL_API_REST_URL,
  BITPORTAL_API_MARKET_URL,
  BITPROTAL_API_TRACE_URL,
  BITPORTAL_API_WEBSOCKET_URL,
  EOS_API_URL,
  BITPORTAL_API_CMS_URL,
  BITPORTAL_API_TERMS_URL,
  BITPORTAL_API_UPDATE_LOG_URL,
  CURRENCY_RATE_URL,
  EOS_EXPLORER_URL,
  BITPORTAL_API_EOS_URL,
  BITPORTAL_WEBSITE_URL,
  ADMIN_API,
  SCAN_API,
  DEFAULT_DECIMALS,
  SS58FORMAT_PREFIX,
  IS_MAINNET
}
