import Config from 'react-native-config'

const ENV = Config.ENV
const BITPORTAL_API_REST_URL = Config.BITPORTAL_API_REST_URL
const BITPORTAL_API_WEBSOCKET_URL = Config.BITPORTAL_API_WEBSOCKET_URL

export {
  ENV,
  BITPORTAL_API_REST_URL,
  BITPORTAL_API_WEBSOCKET_URL
}
