import Config from 'react-native-config'

const ENV = Config.ENV
const BITPORTAL_API_REST_URL = Config.BITPORTAL_API_REST_URL
const BITPORTAL_API_WEBSOCKET_URL = Config.BITPORTAL_API_WEBSOCKET_URL
const EOS_API_URL = Config.EOS_API_URL
const BITPORTAL_API_CMS_URL = Config.BITPORTAL_API_CMS_URL

export {
  ENV,
  BITPORTAL_API_REST_URL,
  BITPORTAL_API_WEBSOCKET_URL,
  EOS_API_URL,
  BITPORTAL_API_CMS_URL
}
