# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
workspace 'bitportal.xcworkspace'

target 'bitportal' do
  pod 'IGListKit', '~> 3.0'
#  pod 'Interactable', :path => '../node_modules/react-native-interactable'
#  # Your 'node_modules' directory is probably in the root of your project,
#  # but if not, adjust the `:path` accordingly
#  pod 'React', :path => '../node_modules/react-native', :subspecs => [
#    'Core',
#    'CxxBridge', # Include this for RN >= 0.47
#    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
#    'RCTText',
#    'RCTNetwork',
#    'RCTWebSocket', # Needed for debugging
#    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
#    # Add any other subspecs you want to use in your project
#  ]
#
#  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  # Third party deps podspec link
#  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
#
#  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'
#
#  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
#
#  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
#
#  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end

target 'RNTableView' do
  project '../node_modules/react-native-tableview/RNTableView.xcodeproj'
  pod 'IGListKit', '~> 3.0'
end
