# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!
workspace 'bitportal.xcworkspace'

target 'bitportal' do
  pod 'IGListKit', '~> 3.0'
  pod 'RNCViewpager', :path => '../node_modules/@react-native-community/viewpager'

  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'

end
