// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.djinni

#pragma once

#include "core.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCore final : ::djinni::JniInterface<::core::Core, NativeCore> {
public:
    using CppType = std::shared_ptr<::core::Core>;
    using CppOptType = std::shared_ptr<::core::Core>;
    using JniType = jobject;

    using Boxed = NativeCore;

    ~NativeCore();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeCore>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeCore>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeCore();
    friend ::djinni::JniClass<NativeCore>;
    friend ::djinni::JniInterface<::core::Core, NativeCore>;

};

}  // namespace djinni_generated
