// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.djinni

#import <Foundation/Foundation.h>
@class BPCore;


@interface BPCore : NSObject

+ (nullable BPCore *)create;

- (nonnull NSString *)pbkdf2:(nonnull NSString *)password
                        salt:(nonnull NSString *)salt
                  iterations:(int32_t)iterations
                      keylen:(int8_t)keylen
                      digest:(nonnull NSString *)digest;

@end
