// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.djinni

#import <Foundation/Foundation.h>
@class BPCore;


@interface BPCore : NSObject

+ (nullable BPCore *)create;

- (nonnull NSString *)pbkdf2:(nonnull NSString *)password
                        salt:(nonnull NSString *)salt
                  iterations:(int32_t)iterations
                      keylen:(int8_t)keylen
                      digest:(nonnull NSString *)digest;

- (nonnull NSString *)scrypt:(nonnull NSString *)password
                        salt:(nonnull NSString *)salt
                           N:(int32_t)N
                           r:(int8_t)r
                           p:(int8_t)p
                       dkLen:(int8_t)dkLen;

@end
